#!/usr/bin/env python3

from openai import OpenAI
import os

client = OpenAI(api_key = os.getenv("OPENAI_API_KEY"))


content = input("input: ") 

ai_system_message = f"Schreibe einen Artikel fuer ein Blog. Das Blog ist für Leser, die längere Zeit von Bornholm aus remote arbeiten, sogenannte digital nomads. Die Leser haben Vorkenntnisse, du musst nicht die Basics erklaeren. Schreibe in lockerem Ton, rede den Leser direkt an in der Du-Form. Schreibe Genderneutrak, zwischen 15-20 Saetze in deutschi, Formuliere den Text mit einer passenden Ueberschrift"

ai_user_message = f"{content} "



completion = client.chat.completions.create(
    model="gpt-4o-mini",
    messages=[
        {"role": "system", "content": ai_system_message},
        {"role": "user", "content": ai_user_message}
    ]
)

answer = (completion.choices[0].message.content)

print(answer)
